name: pipes
description: AngularDart API Examples for Pipes
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.32.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha

dev_dependencies:
  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.3.0
